"""Initial migration.

Revision ID: 37e8e2b06024
Revises: 
Create Date: 2023-10-21 10:11:05.926361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e8e2b06024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_token', sa.String(length=1000), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('priority_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('priority_color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'task', ['parent_id'], ['id'])
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tags',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('priority_color',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('priority_title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(FALSE)'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('google_token')

    # ### end Alembic commands ###
